feat: добавлена логика доски
nbitwise/reversi-deeplay pull request #2
Opened 2023-07-27 08:01 UTC by lpycukl

Добавлена логика и тесты на доску.

2023-07-27 09:37 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
Для проверки ходов имеет смысл реализовать парсер доски. Чтобы ему на вход передавать человеко-читаемую строку, а он по ней создавал доску. Ну и, разумеется, тесты на него.
Строка может быть такого вида:
final String boardStr = "" +
"_ _ _ _ _ _ _ _" +

"_ _ _ _ _ _ _ _" +

"_ _ _ _ _ _ _ _" +

"_ _ _ b w _ _ _" +

"_ _ _ w b _ _ _" +

"_ _ _ _ _ _ _ _" +

"_ _ _ _ _ _ _ _" +

"_ _ _ _ _ _ _ _";
Надо составить разные строки и протестировать разные ситуации после хода.
Для теста необходимо 2 доски: состояние до хода и состояние после хода. На первой делается ход и сравнивается со второй. Для этого доске нужны методы equals и hashCode

2023-07-27 09:38 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    //зачем нужен копибоард?
Метод совершения хода должен возвращать доску, на которой совершен ход

2023-07-27 09:49 UTC, lpycukl commented on src/main/java/io/deeplay/Disk.java
> +    BLACK, WHITE
я думал о EMPTY, изначально так и делал. Но подумал, что это какой-то, типа, костыль, потому что не существует пустой фишки, поэтому лучше null?

2023-07-27 09:52 UTC, nbitwise commented on src/main/java/io/deeplay/Disk.java
> +    BLACK, WHITE
А, если добавим EMPTY, то это по смыслу уже не Disk, а Cell

2023-07-27 09:56 UTC, nbitwise commented
А еще можно немного наперед забежать. И сделать интерфейс Board, куда попадут публичные методы. А данную реализацию назвать ArrayBoard, например

2023-07-27 10:07 UTC, nbitwise commented on src/main/java/io/deeplay/Disk.java
> +    BLACK, WHITE
Тогда возвращать из методов придется null - это плохой тон и риск словить исключение

2023-07-27 12:24 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    private boolean isValidMove(int row, int col, Player player) { //проверка, является ли клетка подходящей для хода указанного игрока(здесь ли реализовывать?)
на классе игрок завязана логика работы метода. По идее можно переписать, что только цвет нужен, но пока оставлю, т.к. не является текущей задачей.

2023-07-27 12:24 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    private boolean hasAvailableMoves(Player player) {
Аналогично предыдущему

2023-07-28 05:57 UTC, nbitwise requested changes

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +            throw new IllegalArgumentException("неверный размер доски");
Сообщения об ошибке с большой буквы, точка в конце.

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +     * установка диска в указанную ячейку
С большой буквы. Точка в конце. Описание аргументов. Посмотрите формат и примеры javadoc

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +        }
Для обработки ошибок try-catch внутри методов не нужен. Нам нужно из метода выбрасывать исключение, а ловить его снаружи, при вызове метода. То есть внутри метода нужен throws. 
Еще есть один момент, просто для информации. IllegalArgumentException - это RuntimeException. Значит, его обработка не обязательна на этапе компиляции, и идея не подсветит. Тут мы исключение бросаем для того, скорее чтобы сообщение подробное написать.

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +     * возвращает значение cell, которое лежит в клетке
То же самое про javadoc

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    public Cell getFromPlace(int row, int col) {
просто get

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +        }
try-catch не нужен

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +     * считает диски указанного цвета
Формат javadoc

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    public int countDisk(Cell cell) {
Просто count. У нас есть аргумент типа Cell с именем cell, поэтому countDisk или countCell избыточно. Стоит принимать во внимание такое правило при наименовании методов.

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
>          return count;
Вообще, для оптимизации лучше завести в классе две переменные: numberOfBlack и numberOfWhite. Нам каждый раз не придется пробегать по массиву, чтобы посчитать. Сможем получать кол-во за константу.
Кол-во пустых в общем случае = size * sizе - numberOfBlack - numberOfWhite

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +        if (row < 0 || row >= boardSize || col < 0 || col >= boardSize || board[row][col] != null) {
1.  Мы поменяли enum Cell, теперь у нас в массиве не может быть null. 
2. Проверку вынести в отдельный метод, который будет бросать исключение при неправильных индексах. Его и использовать во всех методах для проверки.
3. Возможно, если мы сюда неправильные индексы передали, то можно оценивать ход как неправильный. НО! это ошибка в ключевой логике игры, которой здесь не должно быть. Мы должны в этом месте "упасть", выдать исключение с подробным сообщением о том, что пошло не так. А потом исправить эту ошибку. Стратегия Fail fast.

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    private boolean isValidMove(int row, int col, Player player) {
И почему мы все еще передаем в аргументы player?!! Только Cell. Доска ничего не знает об игроке. Она работает с конкретным цветом фишки

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    private boolean hasAvailableMoves(Player player) {
Тип клетки нужен, а не игрок

2023-07-28 05:57 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    public void setOnPlace(int row, int col, Cell cell) {
просто set

2023-07-28 05:57 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(Cell.BLACK, board.getFromPlace(3,4));
Почему проверки только 3? Нужно проверить, что 4 фишки в центре правильные. А все остальные пустые.

2023-07-28 05:57 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(Cell.WHITE, board.getFromPlace(3,3));
хорошо бы 3 проверки: на черную, белую, пустую
+ отдельный тест на ошибку при неправильных индексах

2023-07-28 05:57 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(2,board.countDisk(Cell.BLACK));
Пробелов нет между аргументами. Используйте сочетание Ctrl+Alt+L, чтобы отформатировать код в соответствие хорошему стилю.

2023-07-28 06:08 UTC, lpycukl commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(Cell.WHITE, board.getFromPlace(3,3));
такая ли в этом есть необходимость, если и белая и черная и пустая - все один enum, одна реализация, и, логично, что если белый достается верно, то и с другими тоже все будет ок?

2023-07-28 06:12 UTC, nbitwise requested changes

2023-07-28 06:12 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> -        } catch (IllegalArgumentException exception) {
else не нужно. Если на throw попадет дальше код все равно не выполнится

2023-07-28 06:12 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +     * Возвращает значение cell, которое лежит в клетке.
Описание аргументов

2023-07-28 06:12 UTC, nbitwise commented on src/main/java/io/deeplay/Cell.java
> +        } else return Cell.BLACK;
Почему по abbreviation сравниваем? Можно делать так: this == BLACK

2023-07-28 06:12 UTC, nbitwise commented on src/main/java/io/deeplay/Cell.java
> +    BLACK("B"), WHITE("W"), EMPTY("E");
Для простоты, символы, конечно ок. Но я считаю, что лишнее. Это ответственность внешнего класса UI сопоставлять тип клетки символу.

2023-07-28 06:12 UTC, nbitwise commented on src/main/java/io/deeplay/Player.java
>  }
Убрать из этого коммита Player. Он здесь не нужен

2023-07-28 06:12 UTC, nbitwise commented on src/main/java/io/deeplay/HumanPlayer.java
>  class HumanPlayer extends Player {
И этот класс из коммита убрать

2023-07-28 06:13 UTC, alekator commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(Cell.BLACK, board.getFromPlace(3,4));
+))))

2023-07-28 06:15 UTC, alekator commented on src/main/java/io/deeplay/Player.java
>  }
Моя работа

2023-07-28 06:15 UTC, alekator commented on src/main/java/io/deeplay/HumanPlayer.java
>  class HumanPlayer extends Player {
это тоже моя работа, в игроке все будет

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public Board(int BOARD_SIZE) { //создание доски.. здесь ли делать проверки на корректность данных? или отдельно, аля в "контроллере"
Done

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    private int deskSize = 0;
Done

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public Board(int BOARD_SIZE) { //создание доски.. здесь ли делать проверки на корректность данных? или отдельно, аля в "контроллере"
Done

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public void setOnPlace(int i, int j, Disk disk) { //установка диска в ячейку
Done

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public void setOnPlace(int i, int j, Disk disk) { //установка диска в ячейку
Done

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public void setOnPlace(int i, int j, Disk disk) { //установка диска в ячейку
Done

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public void setOnPlace(int i, int j, Disk disk) { //установка диска в ячейку
Done

2023-07-28 06:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public Board(int BOARD_SIZE) { //создание доски.. здесь ли делать проверки на корректность данных? или отдельно, аля в "контроллере"
Done

2023-07-28 06:26 UTC, lpycukl commented on src/main/java/io/deeplay/Disk.java
> +    BLACK, WHITE
Done

2023-07-28 06:26 UTC, lpycukl commented on src/main/java/io/deeplay/HumanPlayer.java
Done

2023-07-28 06:26 UTC, lpycukl commented on src/main/java/io/deeplay/Player.java
Done

2023-07-28 06:26 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    private boolean hasAvailableMoves(Player player) {
Done

2023-07-28 06:26 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
Done

2023-07-28 06:26 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +            throw new IllegalArgumentException("неверный размер доски");
Done

2023-07-28 06:33 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +     * установка диска в указанную ячейку
Done

2023-07-28 06:33 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +        }
Done

2023-07-28 06:33 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +     * возвращает значение cell, которое лежит в клетке
Done

2023-07-28 06:34 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public Cell getFromPlace(int row, int col) {
Done

2023-07-28 06:34 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +        }
Done

2023-07-28 06:34 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +     * считает диски указанного цвета
Done

2023-07-28 06:35 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public int countDisk(Cell cell) {
Done

2023-07-28 06:37 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    private boolean isValidMove(int row, int col, Player player) {
Done

2023-07-28 06:38 UTC, lpycukl commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(Cell.BLACK, board.getFromPlace(3,4));
Done

2023-07-28 06:38 UTC, lpycukl commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(2,board.countDisk(Cell.BLACK));
Done

2023-07-28 06:38 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +        if (row > BOARD_SIZE - 1 || row < 0 || col > BOARD_SIZE - 1 || col < 0) {
Done

2023-07-28 06:38 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> -        } catch (IllegalArgumentException exception) {
Done

2023-07-28 06:38 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +     * Возвращает значение cell, которое лежит в клетке.
Done

2023-07-28 06:38 UTC, lpycukl commented on src/main/java/io/deeplay/Cell.java
> +        } else return Cell.BLACK;
Done

2023-07-28 06:38 UTC, lpycukl commented on src/main/java/io/deeplay/Cell.java
> +    BLACK("B"), WHITE("W"), EMPTY("E");
Done

2023-07-28 06:39 UTC, lpycukl commented on src/main/java/io/deeplay/Player.java
>  }
Done

2023-07-28 06:39 UTC, lpycukl commented on src/main/java/io/deeplay/HumanPlayer.java
>  class HumanPlayer extends Player {
Done

2023-07-28 07:07 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(Cell.WHITE, board.getFromPlace(3,3));
А если реализацию изменим?

2023-07-28 07:22 UTC, lpycukl commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(Cell.WHITE, board.getFromPlace(3,3));
Done

2023-07-28 07:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    public void setOnPlace(int row, int col, Cell cell) {
Done

2023-07-28 07:23 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +        if (row < 0 || row >= boardSize || col < 0 || col >= boardSize || board[row][col] != null) {
Александр этим займется

2023-07-28 07:24 UTC, lpycukl commented on src/test/java/io/deeplay/BoardTest.java
Этим займется Илья

2023-07-28 07:24 UTC, lpycukl commented on src/main/java/io/deeplay/Board.java
> +    }
Этим займется Александр

2023-07-28 07:59 UTC, nbitwise requested changes

2023-07-28 07:59 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    private int quantityOfEmpty = BOARD_SIZE * BOARD_SIZE;
Это можно не хранить, а вычитать кол-во черных и белых из кол-ва всех клеток. Я же писал

2023-07-28 07:59 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
>          if (row > BOARD_SIZE - 1 || row < 0 || col > BOARD_SIZE - 1 || col < 0) {
>= BOARD_SIZE так читабельнее

2023-07-28 07:59 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        assertThrows(IllegalArgumentException.class,()->board.set(-2, 3, Cell.WHITE));
Опять пробелов нет. Ctrl + Alt + L

2023-07-28 07:59 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
>      Board board = new Board();
У тебя тут одна доска на все. Ее каждый тест будет менять. Это очень плохо. Потом какой-нибудь тест упадет из-за невалидных данных. Получается, что у тебя успех выполнения тестов зависит от их порядка. Так быть не должно.

Либо в каждом тесте создавать свою новую доску. Либо сделать метод setUp, который будет инициализировать ее перед каждым тестом.

```Java
Board board;

@BeforeEach // Будет выполнять метод перед запуском каждого теста
void setUp() {
    board = new Board();
}
```

2023-07-28 07:59 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
>          }
Писал же, что проверку на границы индексов нужно вынести в отдельный метод. Если они вылазят, то нужно исключение выкидывать, а не false возвращать.  
И этот метод проверки использовать везде, куда индексы передаются

2023-07-28 07:59 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +    void quantity() {
Плохое название для теста. Оно должно отражать, что тестируем. Например getCellsQuantity() или testGetCellsQuantity()

2023-07-28 07:59 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +        }
Это в отдельный метод

2023-07-28 07:59 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +        quantityOfWhite += 2;
Тут можно просто = )

2023-07-28 08:51 UTC, nbitwise requested changes

2023-07-28 08:51 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
> +    private int quantityOfEmpty = BOARD_SIZE * BOARD_SIZE - 4;
quantityOfEmpty хранить не нужно. Мы в методе получения можем высчитывать

2023-07-28 08:51 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
>          return quantityOfEmpty;
BOARD_SIZE * BOARD_SIZE - quantityOfBlack - quantityOfWhite

2023-07-28 08:51 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        // Будет выполнять метод перед запуском каждого теста
Убрать этот комментарий

2023-07-28 08:51 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> -        assertThrows(IllegalArgumentException.class,()->board.set(-2, 3, Cell.WHITE));
Пробелы

2023-07-28 08:51 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> -        assertThrows(IllegalArgumentException.class,()->board.get(-2, 3));
Пробелы

2023-07-28 09:12 UTC, nbitwise approved these changes

2023-07-28 09:12 UTC, merged