feat: Добавлены модули с логикой, локальным запуском игры.
nbitwise/reversi-deeplay pull request #24
Opened 2023-08-11 05:47 UTC by v1023774

Вынесена в отдельный модуль логика игры, к которому будут подключаться в модуле клиента и в модуле сервера.

2023-08-11 07:11 UTC, nbitwise requested changes

2023-08-11 07:11 UTC, nbitwise commented on GameLogic/src/main/java/GameLogging/BoardParser.java
BoardParser не относится к логированию

2023-08-11 07:11 UTC, nbitwise commented on LocalGame/build.gradle
localgame

2023-08-14 10:30 UTC, nbitwise approved these changes

2023-08-14 10:34 UTC, alekator submitted a review, later dismissed

2023-08-14 10:37 UTC, alekator approved these changes

2023-08-14 10:56 UTC, merged