INSHIP-153
nbitwise/reversi-deeplay pull request #25
Opened 2023-08-14 05:55 UTC by lpycukl

feat: создан модуль сервера и реализован класс Server

2023-08-14 06:07 UTC, v1023774 submitted a review, later dismissed

2023-08-14 08:02 UTC, nbitwise commented on server/src/main/java/server/Server.java
> +                int roomId = 1;
Что за хардкод? Почему всегда 1?

2023-08-14 08:02 UTC, nbitwise commented on server/src/main/java/server/Server.java
> +            }));*/
закомментированный код не должен в коммит попадать

2023-08-14 08:22 UTC, nbitwise commented on server/src/test/java/serverTest/ServerTest.java
> +                JsonObject convertedObject = new Gson().fromJson(serverWord, JsonObject.class);
Для него статический экземпляр можно создать в классе теста.

2023-08-14 08:27 UTC, nbitwise commented on server/src/test/java/serverTest/ServerTest.java
> +        try {
Что за вложенный try-catch?) Блок finally можно писать после блока catch. 
А вообще, в тестах не нужен try-catch, тест должен падать, если вылетело исключение. Только если мы не тестируем какой-то конкретный случай, например, как наш код отработает при исключении.

2023-08-14 08:27 UTC, nbitwise commented on server/src/test/java/serverTest/ServerTest.java
> +                String testRequest = "{\"command\":\"registration\",\"nickname\":\"Andrew\"}";
Можно создать объект реквеста и его уже в json сериализовать при помощи Gson

2023-08-14 08:29 UTC, nbitwise commented on server/src/main/java/server/Server.java
> +            throw new RuntimeException(e);
Ты, я так понимаю, просто из примера скопировал. Подумай, надо ли ловить исключение и выкидывать другое. Если да, то зачем?

2023-08-14 08:37 UTC, alekator commented on server/src/main/java/server/Server.java
> +            }));*/
у меня в коде нет этого, я без понятия че это такое

2023-08-14 08:55 UTC, alekator commented on server/src/main/java/server/Server.java
> +            throw new RuntimeException(e);
Клиент процессор под наши задачи переделать надо

2023-08-14 08:55 UTC, alekator commented on server/src/test/java/serverTest/ServerTest.java
> +
Убери из тестов try catch вообще,

2023-08-14 10:04 UTC, lpycukl commented on server/src/main/java/server/Server.java
> +            }));*/
done

2023-08-14 10:04 UTC, lpycukl commented on server/src/test/java/serverTest/ServerTest.java
> +                JsonObject convertedObject = new Gson().fromJson(serverWord, JsonObject.class);
done

2023-08-14 10:06 UTC, lpycukl commented on server/src/test/java/serverTest/ServerTest.java
> +        try {
done

2023-08-14 10:07 UTC, lpycukl commented on server/src/test/java/serverTest/ServerTest.java
> +                String testRequest = "{\"command\":\"registration\",\"nickname\":\"Andrew\"}";
Я не делал отдельно объекты реквестов в реализации сервера, все через json обрабатывается. только для респонсов

2023-08-14 10:16 UTC, lpycukl commented on server/src/test/java/serverTest/ServerTest.java
> +
done

2023-08-14 10:17 UTC, lpycukl commented on server/src/main/java/server/Server.java
> +            throw new RuntimeException(e);
я не совсем понимаю, в чем вопрос

2023-08-14 10:27 UTC, lpycukl commented on server/src/main/java/server/Server.java
> +            throw new RuntimeException(e);
done

2023-08-14 10:33 UTC, alekator requested changes

2023-08-14 10:33 UTC, alekator commented on server/src/test/java/serverTest/ServerTest.java
> +            String serverWord = in.readLine();
Нужны модификаторы доступа для всех переменных

2023-08-14 10:35 UTC, alekator requested changes

2023-08-15 04:26 UTC, v1023774 submitted a review, later dismissed

2023-08-15 05:11 UTC, alekator submitted a review, later dismissed

2023-08-15 05:15 UTC, nbitwise requested changes

2023-08-15 05:15 UTC, nbitwise commented on server/src/test/java/serverTest/ServerTest.java
> +        final String testRequest = "{\"command\":\"authorization\",\"nickname\":\"Andrew\"}";
Объект реквеста создавать надо и его сериализовывать, а не вручную строчку писать

2023-08-15 05:17 UTC, lpycukl commented on server/src/test/java/serverTest/ServerTest.java
> +        final String testRequest = "{\"command\":\"authorization\",\"nickname\":\"Andrew\"}";
У меня нет объекта реквест

2023-08-15 06:12 UTC, alekator approved these changes

2023-08-15 06:43 UTC, nbitwise commented on server/src/main/java/server/Server.java
> +
Что за огромный пробел?)

2023-08-15 06:44 UTC, nbitwise commented on server/src/main/java/server/Server.java
> +        }
Почему catch пустой? Надо хотя бы логировать

2023-08-15 06:51 UTC, nbitwise requested changes

2023-08-15 06:51 UTC, nbitwise commented on server/src/main/java/responses/ResponseAutorization.java
AuthorizationResponse. h не хватает после t. Слово Response вторым идет

2023-08-15 06:51 UTC, nbitwise commented on server/src/main/java/server/Server.java
> +                RegistrationRequest request = gson.fromJson(jsonRequest, RegistrationRequest.class);
Я не пойму, откуда ты RegistrationRequest берешь? В коммите не вижу

2023-08-15 06:53 UTC, nbitwise commented on server/src/main/java/responses/ResponseAutorization.java
Это всех классов касается

2023-08-15 08:20 UTC, lpycukl commented on server/src/main/java/server/Server.java
> +                RegistrationRequest request = gson.fromJson(jsonRequest, RegistrationRequest.class);
Забыл добавить, исправлю в новой ветке

2023-08-15 08:22 UTC, lpycukl commented on server/src/main/java/responses/ResponseAutorization.java
done

2023-08-15 09:09 UTC, nbitwise submitted a review, later dismissed

2023-08-15 10:44 UTC, v1023774 approved these changes

2023-08-15 11:38 UTC, merged