feat: добавлен класс Parser
nbitwise/reversi-deeplay pull request #3
Opened 2023-07-28 10:10 UTC by v1023774

Добавлен основной метод parser, который конвертирует достку из строкового формата в объект Board. Добавлен тест для написанного метода parser в класс BoardTest.

2023-07-28 10:35 UTC, nbitwise requested changes

2023-07-28 10:35 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
Этот класс почему сюда попал? Не должен

2023-07-28 10:35 UTC, nbitwise commented on src/main/java/io/deeplay/Board.java
И это старая версия. Обнови проект перед пушем

2023-07-28 10:35 UTC, nbitwise commented on src/main/java/io/deeplay/Parser.java
> +    public static Board parser(String boardinstring){
Символы модно в аргументы передавать. Стоит еще добавить символ пустой клетки. Чтобы в строку можно было бы добавить пробелы. Так читабельнее.
Имя поменяй на boardAsString. Чтобы и с точки зрения английского, и с точки зрения наименования в camelCase было правильно.

2023-07-28 10:35 UTC, nbitwise commented on src/main/java/io/deeplay/Parser.java
Переменным добавь final

2023-07-28 10:35 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +    void parser(){
testParsing

2023-07-28 10:35 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        Board boardparse = Parser.parser("________\n" +
Добавить бы еще кейсов. А еще протестировать кейс, когда количество значащих символов (не учитывая пробелы) не соответствующее (!= 64)

2023-07-28 10:35 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +        assertEquals(board, boardparse);
parsedBoard

2023-07-28 10:35 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +    void parser(){
Тест на парсер доски должен быть в отдельном классе

2023-07-31 04:35 UTC, nbitwise commented on src/main/java/io/deeplay/Parser.java
> +    public static Board parser(String boardinstring){
название метода - глагол (что делает?), parse()

2023-07-31 05:22 UTC, lpycukl approved these changes

2023-07-31 05:41 UTC, nbitwise requested changes

2023-07-31 05:41 UTC, nbitwise commented on src/main/java/io/deeplay/Parser.java
> +                char currentCell = boardAsString.charAt((Board.getBOARD_SIZE()*2 + 1) * row + col);
Не пойму, почему getBOARD_SIZE()? По любым правилам это наименование неправильное. getBoardSize даже если это константа. А лучше просто getSize(). И не статический.

2023-07-31 05:41 UTC, nbitwise commented on src/test/java/io/deeplay/ParserTest.java
> +                            "_ _ _ _ _ _ _ _ \n" +
Это в отдельном тесте должно быть

2023-07-31 05:41 UTC, nbitwise commented on src/test/java/io/deeplay/ParserTest.java
> +    }
Если у нас один тестовый метод, то setUp с BeforeEach не нужен. Внутри теста создавай .

2023-07-31 05:41 UTC, nbitwise commented on src/test/java/io/deeplay/ParserTest.java
> +                            "_ _ _ _ _ _ _ _ \n" +
В идеале сначала инициализация данных, а потом все ассерты вместе. Не стоит разбрасывать их по всему тесту.

```Java
final Board expectedBoard1 = new Board();
final Board parsedBoard1 = Parser.parse(...);
final Board expectedBoard2 = new Board();
final Board parsedBoard2 = Parser.parse(...);
...
assertEquals(expectedBoard1, parsedBoard1);
assertEquals(expectedBoard2, parsedBoard2);
```

2023-07-31 05:41 UTC, nbitwise commented on src/test/java/io/deeplay/ParserTest.java
> +        Board parsedBoard = Parser.parse(
не вижу final

2023-07-31 05:41 UTC, nbitwise commented on src/main/java/io/deeplay/Parser.java
>  public class Parser {
BoardParser

2023-07-31 06:53 UTC, nbitwise requested changes

2023-07-31 06:53 UTC, nbitwise commented on src/main/java/io/deeplay/BoardParser.java
> +        if (boardAsString.length() < (board.getSize() * 2 + 1) * board.getSize() - 2)
1. В тесте не надо проверять корректность входных данных. Ты их тут сам задаешь. Нужно в отдельном тесте делать проверку на то, что парсер корректно отрабатывает в таких случаях. То есть выбрасывает понятное ожидаемое исключение.
2. У if всегда должны быть {}. Без скобок можно обойтись, если в теле только что-то совсем короткое, как return, brake или continue

2023-07-31 07:02 UTC, v1023774 commented on src/main/java/io/deeplay/BoardParser.java
> +        if (boardAsString.length() < (board.getSize() * 2 + 1) * board.getSize() - 2)
Исправил первое, запушил, заметил, что нет скобок у if, запушил еще раз с исправлением второго.

2023-07-31 07:28 UTC, nbitwise requested changes

2023-07-31 07:28 UTC, nbitwise commented on src/main/java/io/deeplay/BoardParser.java
> -        if (boardAsString.length() < (board.getSize() * 2 + 1) * board.getSize() - 2)
Прошу прощения) Я не увидел, что это в BoardParser.
Было норм. Только скобки добавить)

2023-07-31 07:28 UTC, nbitwise commented on src/test/java/io/deeplay/ParserTest.java
> -        assertThrows(IllegalArgumentException.class, () -> BoardParser.parse(
Вернуть на IllegalArgumentException

2023-07-31 07:41 UTC, nbitwise approved these changes

2023-07-31 07:42 UTC, merged