feat: Обновлен метод isValidMove
nbitwise/reversi-deeplay pull request #5
Opened 2023-07-31 10:11 UTC by lpycukl

Обновлен метод isValidMove, добавлены тесты к нему

2023-07-31 10:27 UTC, v1023774 submitted a review, later dismissed

2023-07-31 11:54 UTC, nbitwise requested changes

2023-07-31 11:54 UTC, nbitwise commented on src/test/java/io/deeplay/BoardTest.java
> +    }
Одного теста мало. Надо разные случаи рассмотреть:

- проверить 
- справа 
- слева
- сверху
- снизу
- по диагонали в разные стороны
- когда пустая клетка в окружении дисков

2023-08-01 05:10 UTC, lpycukl commented on src/test/java/io/deeplay/BoardTest.java
> +    }
Done

2023-08-01 06:14 UTC, v1023774 requested changes

2023-08-01 06:14 UTC, v1023774 commented on src/test/java/io/deeplay/BoardTest.java
> +        Board board1 = BoardParser.parse(
final board

2023-08-01 06:14 UTC, v1023774 commented on src/test/java/io/deeplay/BoardTest.java
> +        Board board2 = BoardParser.parse(
final

2023-08-01 07:53 UTC, v1023774 approved these changes

2023-08-01 08:13 UTC, closed without merging